### ISSUE TITLE
Solitaire: fix bug with refreshing stock pile

### ISSUE THREAD

**Issue by alyssagchoi** [dhmit/french-playing-cards#6]
When refreshing the stock, the waste doesn't fully empty out and there's still one card left in the waste after refreshing the stock. After doing a lot of print statements, it seems that the stack correctly fully empties out at the end of the `refreshStock` function, but sometime during the rendering, one of the cards from the stock gets moved back to the waste.

**Comment by ryaanahmed** [comment]
handleStockClick was getting called at the same time as the call to refresh the stock, as it was bound to the onclick of the stock containing div, not the card image.
